FROM debian:buster-slim 
#RUN echo 'deb http://deb.debian.org/debian buster-backports main' > /etc/apt/sources.list.d/backports.list
#RUN DEBIAN_FRONTEND=noninteractive apt-get -yq install {your- pkgs}
 
RUN apt-get update
RUN apt-get - upgrade
RUN apt-get install --no-install-suggests -y ca-certificates php7.3 php7.3-fpm php7.3-common php7.3-mysql php7.3-zip \
    php7.3-mbstring php7.3-xml php7.3-curl php7.3-sqlite3 php7.3-xml php7.3-gd php-common php-imagick imagemagick \
    apache2
 
# configuration php
RUN echo "[www]" > /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "user = www-data" >> /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "group = www-data" >> /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "listen = 0.0.0.0:9000" >> /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "listen.owner = www-data" >> /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "listen.group = www-data" >> /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "pm = dynamic" >> /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "pm.max_children = 5" >> /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "pm.start_servers = 2" >> /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "pm.min_spare_servers = 1" >> /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "pm.max_spare_servers = 3" >> /etc/php/7.3/fpm/pool.d/www.conf 

RUN echo "daemonize = no" > /etc/php/7.3/fpm/pool.d/www.conf \
    && echo "include=/etc/php/7.3/pool.d/*.conf" >> /etc/php/7.3/fpm/php-fpm.conf

RUN echo "max_execution_time = 200" >>  /etc/php/7.3/fpm/php.ini \
    && echo "post_max_size 100M" >> /etc/php/7.3/fpm/php.ini \
    && echo "upload_max_filesize = 20M" >> /etc/php/7.3/fpm/php.ini \
    && echo "memory_limit = 256M" >> /etc/php/7.3/fpm/php.ini 


# Configuration apache
ENV APACHE_DOCUMENT_ROOT /path/to/new/root
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf 

ENV DOLI_VERSION 9.0.0

RUN apt-get install wget
#RUN DEBIAN_FRONTEND=noninteractive apt-get -yq install {your- pkgs} 

ADD . /app/
WORKDIR /app
RUN wget -q https://github.com/Dolibarr/dolibarr/archive/${DOLI_VERSION}.tar.gz \
    && tar xf ${DOLI_VERSION}.tar.gz \
    && mv dolibarr-${DOLI_VERSION}/htdocs/* /var/www/html \
    && rm -rf dolibarr-${DOLI_VERSION} ${DOLI_VERSION}.tar.gz 


  

      #&& mv dolibarr-${DOLI_VERSION}/htdocs/* /var/www/html \

EXPOSE 8080
VOLUME /var/www/html /var/www/html/conf /var/www/html/documents

RUN apt-get clean && rm -rf /var/lib/apt/lists/*
CMD ["php-fpm7.3"]
