apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dolibarr
  name: dolibarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dolibarr
    spec:
      containers:
      - env:
        - name: DOLI_DB_HOST
          value: mariadb
        - name: DOLI_DB_NAME
          value: dolibarr
        - name: DOLI_DB_PASSWORD
          value: BOLEYN
        - name: DOLI_DB_USER
          value: dolibar
        image: ocr-docker-build
        name: dolibarr
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: dolibar-html
        - mountPath: /var/www/documents
          name: dolibarr-docs
        - mountPath: /var/lib/mysql
          name: dolibar-db
      restartPolicy: Always
      volumes:
      - name: dolibar-html
        persistentVolumeClaim:
          claimName: dolibar-html
      - name: dolibarr-docs
        persistentVolumeClaim:
          claimName: dolibarr-docs
      - name: dolibar-db
        persistentVolumeClaim:
          claimName: dolibar-db
status: {}
